### ISSUE TITLE
Crontab may be wrong

### ISSUE THREAD

**Issue by NekoShinobi** [SiwatINC/humhub#1]
Crontab previously is written like
```
* * * * * /usr/bin/php7.3 /config/www/humhub/protected/yii queue/run >/dev/null 2>&1
* * * * * /usr/bin/php7.3 /config/www/humhub/protected/yii cron/run >/dev/null 2>&1
```

I believe it should be
`/config/www/protected/yii` instead

**Comment by SiwatS** [comment]
I originally write this to mean, run /config/www/humhub/protected/yii with arguments queue/run and cron/run, dump output to /dev/null using php7.3, is it not functioning anymore?, I am not running the container anymore.

**Comment by NekoShinobi** [comment]
The commands work fine once the path is fixed, just the folder structure doesn't seem to have the `/humhub/` portion of it anymore - When I ran the container yesterday on unraid I noticed the folder structure was `/config/www/protected/yii` instead of `/config/www/humhub/protected/yii`

This was my first time running it, so I don't know if it's because something changed or something else
